{
 "title": "Connect / Server",
 "description": "Common visualisations of gRPC (Golang) Server metrics",
 "tags": [
  "connect",
  "server"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "package",
    "label": "Package",
    "query": {
     "query": "label_values(connect_server_started_total, package)"
    }
   },
   {
    "name": "call",
    "label": "Call",
    "query": {
     "query": "label_values(connect_server_started_total{package=~\"$package\"}, call)"
    }
   },
   {
    "name": "type",
    "label": "Type",
    "query": {
     "query": "label_values(connect_server_started_total{package=~\"$package\", call=~\"$call\"}, call_type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests started [1m]",
   "type": "timeseries",
   "description": "Rate of gRPC requests started",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(increase(connect_server_started_total{package=~\"$package\", call=~\"$call\", call_type=~\"$type\"}[1m])) by (package, call)",
     "legendFormat": "{{package}}.{{call}}"
    }
   ]
  },
  {
   "title": "Requests completed [1m]",
   "type": "timeseries",
   "description": "Rate of requests completed, by status",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(increase(connect_server_handled_seconds_count{package=~\"$package\", call=~\"$call\", call_type=~\"$type\"}[1m])) by (package, call, code)",
     "legendFormat": "{{package}}.{{call}} - {{code}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Request errors [1m]",
   "type": "timeseries",
   "description": "Rate of errors, by status",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(increase(connect_server_handled_seconds_count{package=~\"$package\", call=~\"$call\", call_type=~\"$type\", code!=\"ok\"}[1m])) by (package, call, code)",
     "legendFormat": "{{grpc_service}}.{{grpc_method}} - {{grpc_code}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "99th percentile response latency [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum(rate(connect_server_handled_seconds_bucket{call_type=~\"$type\", package=~\"$package\", call=~\"$call\"}[5m])) by (package, call, le)\n)\n\n",
     "legendFormat": "{{package}}.{{call}}"
    }
   ]
  }
 ]
}