{
 "title": "Kubernetes / Applications",
 "description": "Aggregate information about applications in k8s",
 "tags": [
  "kubernetes",
  "application"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(up, cluster)" } },
   { "name": "job", "query": { "query": "label_values(up, job)" } },
   { "name": "pod", "query": { "query": "label_values(up, pod)" } }
  ]
 },
 "panels": [
  { "title": "Application resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{cluster=~\"$cluster\", job=~\"$job\", pod=~\"$pod\"}) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total CPU usage (vCPUs) [5m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{cluster=~\"$cluster\", job=~\"$job\", pod=~\"$pod\"}[5m])) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Horizontal Scaling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Replica count [1m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(up{cluster=~\"$cluster\", job=~\"$job\", pod=~\"$pod\"}[1m]) by (job)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}