{
 "title": "Gitpod / Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(gitpod_ws_manager_mk2_workspace_phase_total, cluster)"
    }
   },
   { "name": "cell", "label": "Cell", "query": { "query": "label_values(cell)" } }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Gitpod Version",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gitpod_version_info{cell=\"$cell\"}) by (gitpod_version)"
    }
   ]
  },
  {
   "title": "Stats(7d)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(sum(gitpod_ws_manager_mk2_workspace_phase_total{phase=\"Running\",cell=\"$cell\"})[7d:10m])",
     "legendFormat": "Avg"
    },
    {
     "expr": "min_over_time(sum(gitpod_ws_manager_mk2_workspace_phase_total{phase=\"Running\",cell=\"$cell\"})[7d:10m])",
     "legendFormat": "Min"
    },
    {
     "expr": "max_over_time(sum(gitpod_ws_manager_mk2_workspace_phase_total{phase=\"Running\",cell=\"$cell\"})[7d:10m])",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Workspaces by phase",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(gitpod_ws_manager_mk2_workspace_phase_total{cell=\"$cell\"}) by (phase)",
     "legendFormat": "{{ label_name }}"
    }
   ]
  },
  {
   "title": "Running workspaces",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(gitpod_ws_manager_mk2_workspace_phase_total{phase=\"Running\",cell=\"$cell\"}) by (cluster,type)",
     "legendFormat": "{{cluster}}: {{type}}"
    }
   ]
  },
  {
   "title": "Gitpod Version",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max(gitpod_version_info{cell=\"$cell\"}) by (gitpod_version)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Running workspaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$cluster: Running Workspaces",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "repeat": "cluster",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(gitpod_ws_manager_mk2_workspace_phase_total{cluster=~\"$cluster\", phase=\"Running\", cell=\"$cell\"}) by (type)",
     "legendFormat": "{{ type }}"
    },
    {
     "expr": "sum(gitpod_ws_manager_mk2_workspace_activity_total{cluster=~\"$cluster\",cell=\"$cell\",active=\"false\"})",
     "legendFormat": "Regular Not Active"
    }
   ]
  },
  {
   "title": "Workspace node's normalized Load Average",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 503 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$cluster: Workspace node's normalized load average",
   "type": "graph",
   "description": "Nodes with a high normalized load average do not represent a real problem, it only means that pods should probably not be scheduled to them.\n\nIf you'd like to see more details about resource consumption of a particular node, you can do so by clicking at the node name.\n",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 504 },
   "repeat": "cluster",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(nodepool:node_load1:normalized{cluster=~\"$cluster\", nodepool=~\".*workspace.*\",cell=\"$cell\"}) by (node))\n",
     "legendFormat": "{{node}}"
    },
    { "expr": "1\n", "legendFormat": "Node Max Load Avg" }
   ]
  },
  {
   "title": "Workspace Startup time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 994 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$cluster: Regular Workspace Startup time",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 995 },
   "repeat": "cluster",
   "targets": [
    {
     "expr": "sum(rate(gitpod_ws_manager_mk2_workspace_startup_seconds_bucket{cluster=~\"$cluster\",type=\"Regular\",cell=\"$cell\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Workspace Phases",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1485 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$cluster: Workspace Phases",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1486 },
   "repeat": "cluster",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (type, phase)(gitpod_ws_manager_mk2_workspace_phase_total{cluster=~\"$cluster\",cell=\"$cell\",phase!=\"Running\"})",
     "legendFormat": "{{type}} - {{phase}}"
    }
   ]
  },
  {
   "title": "Workspace failures",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1976 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$cluster: Workspace Failures per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1977 },
   "repeat": "cluster",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(gitpod_ws_manager_mk2_workspace_stops_total{cluster=~\"$cluster\",cell=\"$cell\",reason=\"failed\"}[5m])\n) by (cluster, type) OR on() vector(0)\n",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Cluster size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2467 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$cluster: Number of nodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2468 },
   "repeat": "cluster",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_node_labels{cluster=~\"$cluster\",cell=\"$cell\"}) by (nodepool)",
     "legendFormat": "{{nodepool}}"
    }
   ]
  }
 ]
}