{
 "title": "Gitpod / Overview Mk2",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(gitpod_ws_manager_mk2_workspace_phase_total, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Stats(7d)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(gitpod_ws_manager_mk2_workspace_phase_total{phase=\"Running\"}[7d]))",
     "legendFormat": "Avg"
    },
    {
     "expr": "sum(min_over_time(gitpod_ws_manager_mk2_workspace_phase_total{phase=\"Running\"}[7d]))",
     "legendFormat": "Min"
    },
    {
     "expr": "sum(max_over_time(gitpod_ws_manager_mk2_workspace_phase_total{phase=\"Running\"}[7d]))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Workspaces by phase",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(gitpod_ws_manager_mk2_workspace_phase_total{}) by (phase)",
     "legendFormat": "{{ label_name }}"
    }
   ]
  },
  {
   "title": "Running workspaces",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(gitpod_ws_manager_mk2_workspace_phase_total{phase=\"Running\"}) by (cluster,type)",
     "legendFormat": "{{cluster}}: {{type}}"
    }
   ]
  },
  {
   "title": "Running workspaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$cluster: Running Workspaces",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "repeat": "cluster",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(gitpod_ws_manager_mk2_workspace_phase_total{cluster=~\"$cluster\", phase=\"Running\"}) by (type)",
     "legendFormat": "{{ type }}"
    },
    {
     "expr": "sum(gitpod_ws_manager_mk2_workspace_activity_total{cluster=~\"$cluster\",active=\"false\"})",
     "legendFormat": "Regular Not Active"
    }
   ]
  },
  {
   "title": "Workspace node's normalized Load Average",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$cluster: Workspace node's normalized load average",
   "type": "graph",
   "description": "Nodes with a high normalized load average do not represent a real problem, it only means that pods should probably not be scheduled to them.\n\nIf you'd like to see more details about resource consumption of a particular node, you can do so by clicking at the node name.\n",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "repeat": "cluster",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(nodepool:node_load1:normalized{cluster=~\"$cluster\", nodepool=~\".*workspace.*\"}) by (node))\n",
     "legendFormat": "{{node}}"
    },
    { "expr": "1\n", "legendFormat": "Node Max Load Avg" }
   ]
  },
  {
   "title": "Workspace Startup time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$cluster: Regular Workspace Startup time",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "repeat": "cluster",
   "targets": [
    {
     "expr": "sum(rate(gitpod_ws_manager_mk2_workspace_startup_seconds_bucket{cluster=~\"$cluster\",type=\"Regular\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Workspace Phases",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$cluster: Workspace Phases",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "repeat": "cluster",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (type, phase)(gitpod_ws_manager_mk2_workspace_phase_total{cluster=~\"$cluster\", phase!=\"Running\"})",
     "legendFormat": "{{type}} - {{phase}}"
    }
   ]
  },
  {
   "title": "Workspace failures",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$cluster: Workspace Failures per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "repeat": "cluster",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(gitpod_ws_manager_mk2_workspace_stops_total{cluster=~\"$cluster\", reason=\"failed\"}[5m])\n) by (cluster, type) OR on() vector(0)\n",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Cluster size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$cluster: Number of nodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "repeat": "cluster",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_node_labels{cluster=~\"$cluster\"}) by (nodepool)",
     "legendFormat": "{{nodepool}}"
    }
   ]
  }
 ]
}