/**
 * Copyright (c) 2022 Gitpod GmbH. All rights reserved.
 * Licensed under the GNU Affero General Public License (AGPL).
 * See License-AGPL.txt in the project root for license information.
 */

// @generated by protoc-gen-es v0.1.1 with parameter "target=ts"
// @generated from file gitpod/v1/prebuilds.proto (package gitpod.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import type {BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage} from "@bufbuild/protobuf";
import {Message, proto3} from "@bufbuild/protobuf";
import {WorkspaceContext} from "./workspaces_pb.js";

/**
 * @generated from message gitpod.v1.GetPrebuildRequest
 */
export class GetPrebuildRequest extends Message<GetPrebuildRequest> {
  /**
   * @generated from field: string prebuild_id = 1;
   */
  prebuildId = "";

  constructor(data?: PartialMessage<GetPrebuildRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "gitpod.v1.GetPrebuildRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "prebuild_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetPrebuildRequest {
    return new GetPrebuildRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetPrebuildRequest {
    return new GetPrebuildRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetPrebuildRequest {
    return new GetPrebuildRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetPrebuildRequest | PlainMessage<GetPrebuildRequest> | undefined, b: GetPrebuildRequest | PlainMessage<GetPrebuildRequest> | undefined): boolean {
    return proto3.util.equals(GetPrebuildRequest, a, b);
  }
}

/**
 * @generated from message gitpod.v1.GetPrebuildResponse
 */
export class GetPrebuildResponse extends Message<GetPrebuildResponse> {
  /**
   * @generated from field: gitpod.v1.Prebuild prebuild = 1;
   */
  prebuild?: Prebuild;

  constructor(data?: PartialMessage<GetPrebuildResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "gitpod.v1.GetPrebuildResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "prebuild", kind: "message", T: Prebuild },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetPrebuildResponse {
    return new GetPrebuildResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetPrebuildResponse {
    return new GetPrebuildResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetPrebuildResponse {
    return new GetPrebuildResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetPrebuildResponse | PlainMessage<GetPrebuildResponse> | undefined, b: GetPrebuildResponse | PlainMessage<GetPrebuildResponse> | undefined): boolean {
    return proto3.util.equals(GetPrebuildResponse, a, b);
  }
}

/**
 * @generated from message gitpod.v1.GetRunningPrebuildRequest
 */
export class GetRunningPrebuildRequest extends Message<GetRunningPrebuildRequest> {
  /**
   * @generated from field: string context_url = 1;
   */
  contextUrl = "";

  constructor(data?: PartialMessage<GetRunningPrebuildRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "gitpod.v1.GetRunningPrebuildRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "context_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetRunningPrebuildRequest {
    return new GetRunningPrebuildRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetRunningPrebuildRequest {
    return new GetRunningPrebuildRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetRunningPrebuildRequest {
    return new GetRunningPrebuildRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetRunningPrebuildRequest | PlainMessage<GetRunningPrebuildRequest> | undefined, b: GetRunningPrebuildRequest | PlainMessage<GetRunningPrebuildRequest> | undefined): boolean {
    return proto3.util.equals(GetRunningPrebuildRequest, a, b);
  }
}

/**
 * @generated from message gitpod.v1.GetRunningPrebuildResponse
 */
export class GetRunningPrebuildResponse extends Message<GetRunningPrebuildResponse> {
  /**
   * @generated from field: gitpod.v1.Prebuild prebuild = 1;
   */
  prebuild?: Prebuild;

  constructor(data?: PartialMessage<GetRunningPrebuildResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "gitpod.v1.GetRunningPrebuildResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "prebuild", kind: "message", T: Prebuild },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetRunningPrebuildResponse {
    return new GetRunningPrebuildResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetRunningPrebuildResponse {
    return new GetRunningPrebuildResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetRunningPrebuildResponse {
    return new GetRunningPrebuildResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetRunningPrebuildResponse | PlainMessage<GetRunningPrebuildResponse> | undefined, b: GetRunningPrebuildResponse | PlainMessage<GetRunningPrebuildResponse> | undefined): boolean {
    return proto3.util.equals(GetRunningPrebuildResponse, a, b);
  }
}

/**
 * @generated from message gitpod.v1.ListenToPrebuildStatusRequest
 */
export class ListenToPrebuildStatusRequest extends Message<ListenToPrebuildStatusRequest> {
  /**
   * @generated from field: string prebuild_id = 1;
   */
  prebuildId = "";

  constructor(data?: PartialMessage<ListenToPrebuildStatusRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "gitpod.v1.ListenToPrebuildStatusRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "prebuild_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListenToPrebuildStatusRequest {
    return new ListenToPrebuildStatusRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListenToPrebuildStatusRequest {
    return new ListenToPrebuildStatusRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListenToPrebuildStatusRequest {
    return new ListenToPrebuildStatusRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListenToPrebuildStatusRequest | PlainMessage<ListenToPrebuildStatusRequest> | undefined, b: ListenToPrebuildStatusRequest | PlainMessage<ListenToPrebuildStatusRequest> | undefined): boolean {
    return proto3.util.equals(ListenToPrebuildStatusRequest, a, b);
  }
}

/**
 * @generated from message gitpod.v1.ListenToPrebuildStatusResponse
 */
export class ListenToPrebuildStatusResponse extends Message<ListenToPrebuildStatusResponse> {
  /**
   * @generated from field: gitpod.v1.PrebuildStatus status = 1;
   */
  status?: PrebuildStatus;

  constructor(data?: PartialMessage<ListenToPrebuildStatusResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "gitpod.v1.ListenToPrebuildStatusResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "status", kind: "message", T: PrebuildStatus },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListenToPrebuildStatusResponse {
    return new ListenToPrebuildStatusResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListenToPrebuildStatusResponse {
    return new ListenToPrebuildStatusResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListenToPrebuildStatusResponse {
    return new ListenToPrebuildStatusResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListenToPrebuildStatusResponse | PlainMessage<ListenToPrebuildStatusResponse> | undefined, b: ListenToPrebuildStatusResponse | PlainMessage<ListenToPrebuildStatusResponse> | undefined): boolean {
    return proto3.util.equals(ListenToPrebuildStatusResponse, a, b);
  }
}

/**
 * @generated from message gitpod.v1.ListenToPrebuildLogsRequest
 */
export class ListenToPrebuildLogsRequest extends Message<ListenToPrebuildLogsRequest> {
  /**
   * @generated from field: string prebuild_id = 1;
   */
  prebuildId = "";

  constructor(data?: PartialMessage<ListenToPrebuildLogsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "gitpod.v1.ListenToPrebuildLogsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "prebuild_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListenToPrebuildLogsRequest {
    return new ListenToPrebuildLogsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListenToPrebuildLogsRequest {
    return new ListenToPrebuildLogsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListenToPrebuildLogsRequest {
    return new ListenToPrebuildLogsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListenToPrebuildLogsRequest | PlainMessage<ListenToPrebuildLogsRequest> | undefined, b: ListenToPrebuildLogsRequest | PlainMessage<ListenToPrebuildLogsRequest> | undefined): boolean {
    return proto3.util.equals(ListenToPrebuildLogsRequest, a, b);
  }
}

/**
 * @generated from message gitpod.v1.ListenToPrebuildLogsResponse
 */
export class ListenToPrebuildLogsResponse extends Message<ListenToPrebuildLogsResponse> {
  /**
   * @generated from field: string line = 1;
   */
  line = "";

  constructor(data?: PartialMessage<ListenToPrebuildLogsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "gitpod.v1.ListenToPrebuildLogsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "line", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListenToPrebuildLogsResponse {
    return new ListenToPrebuildLogsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListenToPrebuildLogsResponse {
    return new ListenToPrebuildLogsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListenToPrebuildLogsResponse {
    return new ListenToPrebuildLogsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListenToPrebuildLogsResponse | PlainMessage<ListenToPrebuildLogsResponse> | undefined, b: ListenToPrebuildLogsResponse | PlainMessage<ListenToPrebuildLogsResponse> | undefined): boolean {
    return proto3.util.equals(ListenToPrebuildLogsResponse, a, b);
  }
}

/**
 * Prebuild describes a prebuild
 *
 * @generated from message gitpod.v1.Prebuild
 */
export class Prebuild extends Message<Prebuild> {
  /**
   * @generated from field: string prebuild_id = 1;
   */
  prebuildId = "";

  /**
   * @generated from field: gitpod.v1.PrebuildSpec spec = 2;
   */
  spec?: PrebuildSpec;

  /**
   * @generated from field: gitpod.v1.PrebuildStatus status = 3;
   */
  status?: PrebuildStatus;

  constructor(data?: PartialMessage<Prebuild>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "gitpod.v1.Prebuild";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "prebuild_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "spec", kind: "message", T: PrebuildSpec },
    { no: 3, name: "status", kind: "message", T: PrebuildStatus },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Prebuild {
    return new Prebuild().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Prebuild {
    return new Prebuild().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Prebuild {
    return new Prebuild().fromJsonString(jsonString, options);
  }

  static equals(a: Prebuild | PlainMessage<Prebuild> | undefined, b: Prebuild | PlainMessage<Prebuild> | undefined): boolean {
    return proto3.util.equals(Prebuild, a, b);
  }
}

/**
 * PrebuildSpec specifies the prebuild input.
 *
 * @generated from message gitpod.v1.PrebuildSpec
 */
export class PrebuildSpec extends Message<PrebuildSpec> {
  /**
   * @generated from field: gitpod.v1.WorkspaceContext context = 1;
   */
  context?: WorkspaceContext;

  /**
   * Incremental prebuilds are based on other prebuilds. If this field is true,
   * expect the context detail to point to another prebuild.
   *
   * @generated from field: bool incremental = 2;
   */
  incremental = false;

  constructor(data?: PartialMessage<PrebuildSpec>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "gitpod.v1.PrebuildSpec";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "context", kind: "message", T: WorkspaceContext },
    { no: 2, name: "incremental", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PrebuildSpec {
    return new PrebuildSpec().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PrebuildSpec {
    return new PrebuildSpec().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PrebuildSpec {
    return new PrebuildSpec().fromJsonString(jsonString, options);
  }

  static equals(a: PrebuildSpec | PlainMessage<PrebuildSpec> | undefined, b: PrebuildSpec | PlainMessage<PrebuildSpec> | undefined): boolean {
    return proto3.util.equals(PrebuildSpec, a, b);
  }
}

/**
 * PrebuildStatus describes the prebuild status.
 *
 * @generated from message gitpod.v1.PrebuildStatus
 */
export class PrebuildStatus extends Message<PrebuildStatus> {
  /**
   * Phase is the prebuild phase we're in
   *
   * @generated from field: gitpod.v1.PrebuildStatus.Phase phase = 1;
   */
  phase = PrebuildStatus_Phase.UNSPECIFIED;

  /**
   * Result indicates what result the prebuild produced, i.e. if it ran
   * successfully or failed for some reason. If phase != done, this field
   * will have RESULT_UNSPECIFIED as value.
   *
   * @generated from field: gitpod.v1.PrebuildStatus.Result result = 2;
   */
  result = PrebuildStatus_Result.UNSPECIFIED;

  /**
   * result_message contains a human readable message describing the prebuild
   * result. E.g. if teh result is SYSTEM_FAILURE, the message describes what
   * that failure was.
   *
   * @generated from field: string result_message = 3;
   */
  resultMessage = "";

  constructor(data?: PartialMessage<PrebuildStatus>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "gitpod.v1.PrebuildStatus";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "phase", kind: "enum", T: proto3.getEnumType(PrebuildStatus_Phase) },
    { no: 2, name: "result", kind: "enum", T: proto3.getEnumType(PrebuildStatus_Result) },
    { no: 3, name: "result_message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PrebuildStatus {
    return new PrebuildStatus().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PrebuildStatus {
    return new PrebuildStatus().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PrebuildStatus {
    return new PrebuildStatus().fromJsonString(jsonString, options);
  }

  static equals(a: PrebuildStatus | PlainMessage<PrebuildStatus> | undefined, b: PrebuildStatus | PlainMessage<PrebuildStatus> | undefined): boolean {
    return proto3.util.equals(PrebuildStatus, a, b);
  }
}

/**
 * @generated from enum gitpod.v1.PrebuildStatus.Phase
 */
export enum PrebuildStatus_Phase {
  /**
   * @generated from enum value: PHASE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: PHASE_PENDING = 1;
   */
  PENDING = 1,

  /**
   * @generated from enum value: PHASE_RUNNING = 2;
   */
  RUNNING = 2,

  /**
   * @generated from enum value: PHASE_DONE = 3;
   */
  DONE = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(PrebuildStatus_Phase)
proto3.util.setEnumType(PrebuildStatus_Phase, "gitpod.v1.PrebuildStatus.Phase", [
  { no: 0, name: "PHASE_UNSPECIFIED" },
  { no: 1, name: "PHASE_PENDING" },
  { no: 2, name: "PHASE_RUNNING" },
  { no: 3, name: "PHASE_DONE" },
]);

/**
 * @generated from enum gitpod.v1.PrebuildStatus.Result
 */
export enum PrebuildStatus_Result {
  /**
   * @generated from enum value: RESULT_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: RESULT_SUCCESS = 1;
   */
  SUCCESS = 1,

  /**
   * @generated from enum value: RESULT_USER_CANCELED = 2;
   */
  USER_CANCELED = 2,

  /**
   * @generated from enum value: RESULT_SYSTEM_FAILURE = 3;
   */
  SYSTEM_FAILURE = 3,

  /**
   * @generated from enum value: RESULT_TASK_FAILURE = 4;
   */
  TASK_FAILURE = 4,
}
// Retrieve enum metadata with: proto3.getEnumType(PrebuildStatus_Result)
proto3.util.setEnumType(PrebuildStatus_Result, "gitpod.v1.PrebuildStatus.Result", [
  { no: 0, name: "RESULT_UNSPECIFIED" },
  { no: 1, name: "RESULT_SUCCESS" },
  { no: 2, name: "RESULT_USER_CANCELED" },
  { no: 3, name: "RESULT_SYSTEM_FAILURE" },
  { no: 4, name: "RESULT_TASK_FAILURE" },
]);

