{
 "title": "Components / server / garbage collection",
 "description": "Dashboard showing periodic garbage collection of DB records",
 "tags": [
  "webapp",
  "server"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Records purged", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Workspaces purged [1h]",
   "type": "timeseries",
   "description": "Number of Workspace records purged in the last 1h",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(gitpod_server_workspaces_purged_total[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workspace Instances purged [1h]",
   "type": "timeseries",
   "description": "Number of Workspace Instance records purged in the last 1h",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(gitpod_server_workspace_instances_purged_total[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prebuilt Workspaces purged [1h]",
   "type": "timeseries",
   "description": "Number of Prebuilt Workspace records purged in the last 1h",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(gitpod_server_prebuild_workspaces_purged_total[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prebuilt Info purged [1h]",
   "type": "timeseries",
   "description": "Number of Prebuilt Info records purged in the last 1h",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(gitpod_server_prebuild_info_purged_total[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prebuilt Workspace Updatable purged [1h]",
   "type": "timeseries",
   "description": "Number of Prebuilt WorkspaceUpdatable records purged in the last 1h",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(increase(gitpod_server_prebuilt_workspace_updatable_purged_total[1h]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}