{
 "title": "Success Criteria",
 "tags": [
  "workspace",
  "success criteria"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Workspace Success Rate Overall",
   "type": "timeseries",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "1-((\n  (\n    sum(rate(gitpod_ws_manager_workspace_stops_total{reason=\"failed\"}[1d])) OR on() vector(0)\n    /\n    sum(rate(gitpod_ws_manager_workspace_stops_total[1d]))\n  )\n) + (\n  (\n    sum(rate(grpc_server_handled_total{grpc_method=\"StartWorkspace\",grpc_code!~\"OK|ResourceExhausted\"}[1d])) OR on() vector(0)\n    /\n    sum(rate(grpc_server_handled_total{grpc_method=\"StartWorkspace\"}[1d]))\n  )\n))",
     "legendFormat": "Success Rate"
    }
   ]
  },
  {
   "title": "Workspace Success Rate Cluster Wise",
   "type": "timeseries",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "1-((\n  (\n    sum by (cluster)(rate(gitpod_ws_manager_workspace_stops_total{reason=\"failed\"}[1d])) OR on() vector(0)\n    /\n    sum by (cluster)(rate(gitpod_ws_manager_workspace_stops_total[1d]))\n  )\n) + (\n  (\n    sum by (cluster)(rate(grpc_server_handled_total{grpc_method=\"StartWorkspace\",grpc_code!~\"OK|ResourceExhausted\"}[1d])) OR on() vector(0)\n    /\n    sum by (cluster)(rate(grpc_server_handled_total{grpc_method=\"StartWorkspace\"}[1d]))\n  )\n))",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "Workspace Startup Time (95% case)",
   "type": "timeseries",
   "gridPos": { "h": 27, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95, \n  sum(\n      rate(gitpod_ws_manager_workspace_startup_seconds_bucket{type!=\"PREBUILD\"}[1d])\n    ) by (le, cluster)\n  )",
     "legendFormat": "{{cluster}}"
    }
   ]
  }
 ]
}