{
 "title": "IDE Startup time",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(supervisor_ide_ready_duration_total_sum, cluster)"
    }
   },
   {
    "name": "kind",
    "query": {
     "query": "label_values(supervisor_ide_ready_duration_total_sum, kind)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "IDE Startup time: ${kind} ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "kind",
   "targets": [
    {}
   ]
  },
  {
   "title": "IDE startup time AVG",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(supervisor_ide_ready_duration_total_sum{kind=~\"${kind}\", cluster=~\"${cluster}\"}) / sum(supervisor_ide_ready_duration_total_count{kind=~\"${kind}\", cluster=~\"${cluster}\"})",
     "legendFormat": "startup time"
    }
   ]
  },
  {
   "title": "IDE startup time quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(le) (rate(supervisor_ide_ready_duration_total_bucket{kind=~\"${kind}\", cluster=~\"${cluster}\"}[$__rate_interval])))",
     "legendFormat": "max"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(supervisor_ide_ready_duration_total_bucket{kind=~\"${kind}\", cluster=~\"${cluster}\"}[$__rate_interval])))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(supervisor_ide_ready_duration_total_bucket{kind=~\"${kind}\", cluster=~\"${cluster}\"}[$__rate_interval])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.8, sum by(le) (rate(supervisor_ide_ready_duration_total_bucket{kind=~\"${kind}\", cluster=~\"${cluster}\"}[$__rate_interval])))",
     "legendFormat": "0.8"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(supervisor_ide_ready_duration_total_bucket{kind=~\"${kind}\", cluster=~\"${cluster}\"}[$__rate_interval])))",
     "legendFormat": "median"
    }
   ]
  },
  {
   "title": "IDE Startup time",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(supervisor_ide_ready_duration_total_bucket{kind=~\"${kind}\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "${cluster}: IDE Startup time",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 28 },
   "repeat": "cluster",
   "targets": [
    {
     "expr": "sum(increase(supervisor_ide_ready_duration_total_bucket{kind=~\"${kind}\", cluster=~\"${cluster}\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}