{
 "title": "Local SSH Reliability",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Local SSH Connection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connection Succeed Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(vscode_desktop_local_ssh_total{phase=\"connected\"}[2m])) / sum(rate(vscode_desktop_local_ssh_total{phase=\"connecting\"}[2m]))",
     "legendFormat": "total ratio"
    }
   ]
  },
  {
   "title": "Failed Reasons",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(vscode_desktop_local_ssh_total{phase=\"failed\"}[2m])) by (failure_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Local SSH Configuration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Ping Extension Server Succeed Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(vscode_desktop_ping_extension_server_total{status=\"success\"}[2m])) / sum(rate(vscode_desktop_ping_extension_server_total{}[2m]))",
     "legendFormat": "total ratio"
    }
   ]
  },
  {
   "title": "Config Failed Reason",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(vscode_desktop_local_ssh_config_total{status=\"failure\"}[2m])) by (failure_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Config Succeed Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(vscode_desktop_local_ssh_config_total{status=\"success\"}[2m])) / sum(rate(vscode_desktop_local_ssh_config_total{}[2m]))",
     "legendFormat": "total ratio"
    }
   ]
  }
 ]
}