{
 "title": "OpenVSX proxy",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{pod=~\"openvsx-proxy.*\"}, cluster)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{cluster=~\"$cluster\", pod=~\"openvsx-proxy.*\"}, node)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{cluster=~\"$cluster\", node=~\"$node\", pod=~\"openvsx-proxy.*\"}, pod)"
    }
   },
   {
    "name": "pod_instance",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}, instance)"
    }
   },
   {
    "name": "container_instance",
    "query": {
     "query": "label_values(up{job=\"openvsx-proxy\", cluster=~\"$cluster\", pod=~\"$pod\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Backup Cache Hits",
   "type": "timeseries",
   "description": "The percentage of responses that can be served from the backup cache on an upstream outage.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(gitpod_openvsx_proxy_backup_cache_hit_total{cluster=~\"$cluster\", pod=~\"$pod\", instance=~\"$container_instance\"}[1m])) / (sum(rate(gitpod_openvsx_proxy_backup_cache_hit_total{cluster=~\"$cluster\", pod=~\"$pod\", instance=~\"$container_instance\"}[1m])) + sum(rate(gitpod_openvsx_proxy_backup_cache_miss_total{cluster=~\"$cluster\", pod=~\"$pod\", instance=~\"$container_instance\"}[1m])))",
     "legendFormat": "backup cache hits"
    }
   ]
  },
  {
   "title": "Regular Cache Hits",
   "type": "timeseries",
   "description": "The percentage of served responses from the regular cache.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(gitpod_openvsx_proxy_regular_cache_hit_and_serve_total{cluster=~\"$cluster\", pod=~\"$pod\", instance=~\"$container_instance\"}[1m])) / (sum(rate(gitpod_openvsx_proxy_regular_cache_hit_and_serve_total{cluster=~\"$cluster\", pod=~\"$pod\", instance=~\"$container_instance\"}[1m])) + sum(rate(gitpod_openvsx_proxy_regular_cache_miss_total{cluster=~\"$cluster\", pod=~\"$pod\", instance=~\"$container_instance\"}[1m])))",
     "legendFormat": "regular cache hits"
    }
   ]
  },
  {
   "title": "Served Responses from Backups Cache",
   "type": "timeseries",
   "description": "The number/percentage of responses that are actually served from the backup cache due to an upstream outage.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(gitpod_openvsx_proxy_backup_cache_serve_total{cluster=~\"$cluster\", pod=~\"$pod\", instance=~\"$container_instance\"}[1m]))",
     "legendFormat": "Served Backups"
    },
    {
     "expr": "sum(rate(gitpod_openvsx_proxy_backup_cache_serve_total{cluster=~\"$cluster\", pod=~\"$pod\", instance=~\"$container_instance\"}[1m])) / sum(rate(gitpod_openvsx_proxy_duration_overall_seconds_count{cluster=~\"$cluster\", pod=~\"$pod\", instance=~\"$container_instance\"}[1m]))",
     "legendFormat": "Served Backups Ratio"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "Number of requests per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(gitpod_openvsx_proxy_duration_overall_seconds_count{cluster=~\"$cluster\", pod=~\"$pod\", instance=~\"$container_instance\"}[1m])",
     "legendFormat": "{{pod}} {{instance}}"
    },
    {
     "expr": "sum(rate(gitpod_openvsx_proxy_duration_overall_seconds_count{cluster=~\"$cluster\", pod=~\"$pod\", instance=~\"$container_instance\"}[1m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Duration Overall Quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(gitpod_openvsx_proxy_duration_overall_seconds_bucket{cluster=~\"$cluster\", pod=~\"$pod\", instance=~\"$container_instance\"}[1m])) by (le))",
     "legendFormat": "100%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(gitpod_openvsx_proxy_duration_overall_seconds_bucket{cluster=~\"$cluster\", pod=~\"$pod\", instance=~\"$container_instance\"}[1m])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(gitpod_openvsx_proxy_duration_overall_seconds_bucket{cluster=~\"$cluster\", pod=~\"$pod\", instance=~\"$container_instance\"}[1m])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.8, sum(rate(gitpod_openvsx_proxy_duration_overall_seconds_bucket{cluster=~\"$cluster\", pod=~\"$pod\", instance=~\"$container_instance\"}[1m])) by (le))",
     "legendFormat": "80%"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(gitpod_openvsx_proxy_duration_overall_seconds_bucket{cluster=~\"$cluster\", pod=~\"$pod\", instance=~\"$container_instance\"}[1m])) by (le))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "Status Code of Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(gitpod_openvsx_proxy_requests_total{cluster=~\"$cluster\", pod=~\"$pod\", instance=~\"$container_instance\"}[1m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Total Number of Requests",
   "type": "table",
   "description": "Table of the total number of requests by path and status. The path is truncated after 3 segments.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(gitpod_openvsx_proxy_requests_total{cluster=~\"$cluster\", pod=~\"$pod\", instance=~\"$container_instance\"}) by (status, path)",
     "legendFormat": "{{path}} {{status}}"
    }
   ]
  },
  {
   "title": "Container image version",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "kube_pod_container_info{cluster=~\"$cluster\", pod=~\"$pod\", image=~\".+\", container=\"openvsx-proxy\"}",
     "legendFormat": "{{cluster}} - {{image}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(container_cpu_usage_seconds_total{container!=\"POD\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)",
     "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Cores being used"
    }
   ]
  },
  {
   "title": "CPU Saturation",
   "type": "graph",
   "description": "Saturation > 100% means that the container is requesting more than its limits.\n\nKubernetes will start to throttle CPU when that happens. That's a sign of degraded performance.\n\n'No Data' indicates that the pod has no CPU limits.",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(container_cpu_usage_seconds_total{container!=\"POD\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)\n/\nsum(\n  kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", cluster=\"$cluster\", pod=~\"$pod\"}\n) by (pod, cluster, node)\n",
     "legendFormat": "{{cluster}} - {{node} - {{pod}} - CPU Saturation"
    },
    {
     "expr": "sum(\nrate(container_cpu_cfs_throttled_seconds_total{container!=\"POD\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod)",
     "legendFormat": "{{pod}} - CPU Throttles"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"POD\", container!=\"\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}) by (pod, cluster, node)",
     "legendFormat": "{{cluster}} - {{node}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Saturation",
   "type": "graph",
   "description": "Memory can't be throttled. When a container reaches 100% of its memory limits,  Kubernetes will kill the container and restart it.\n\n'No Data' indicates that the pod doesn't have Memory limits.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\nrate(container_memory_working_set_bytes{container!=\"POD\", container!=\"\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)\n/\nsum(\n  kube_pod_container_resource_limits{container!=\"POD\", cluster=\"$cluster\", pod=~\"$pod\", resource=\"memory\"}\n) by (pod, cluster, node)\n",
     "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Memory Saturation"
    }
   ]
  },
  {
   "title": "Network Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum (\n  rate(container_network_receive_bytes_total{container!=\"POD\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)",
     "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Received"
    },
    {
     "expr": "sum (\n  rate(container_network_transmit_bytes_total{container!=\"POD\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)",
     "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Transmitted"
    }
   ]
  },
  {
   "title": "Network Saturation (Packets Dropped)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum (\n  rate(container_network_receive_packets_dropped_total{container!=\"POD\", pod!=\"\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)",
     "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Receive"
    },
    {
     "expr": "sum (\n  rate(container_network_transmit_packets_dropped_total{container!=\"POD\", pod!=\"\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)",
     "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Transmit"
    }
   ]
  },
  {
   "title": "Network Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "Errors/s" }
   ],
   "targets": [
    {
     "expr": "sum (\n  rate(container_network_receive_errors_total{container!=\"POD\", pod!=\"\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)",
     "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Received"
    },
    {
     "expr": "sum (\n  rate(container_network_transmit_errors_total{container!=\"POD\", pod!=\"\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)",
     "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Transmitted"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kube_pod_container_status_restarts_total{cluster=~\"$cluster\", pod=~\"$pod\"}[1m])",
     "legendFormat": "{{cluster}} - {{pod}} "
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_running{cluster=~\"$cluster\", pod=~\"$pod\"} == 1 ",
     "legendFormat": "{{cluster}} - {{node}} - {{pod}}  - RUNNING"
    },
    {
     "expr": "(\n  sum by (pod) (kube_pod_container_status_terminated{cluster=~\"$cluster\", pod=~\"$pod\"}) == 1\n) * on(pod) group_left(reason) (\n  sum by (pod, reason) (kube_pod_container_status_terminated_reason{cluster=~\"$cluster\", pod=~\"$pod\"}) == 1\n)",
     "legendFormat": "{{cluster}} - {{node}} - {{pod}}  - TERMINATED -> {{reason}}"
    },
    {
     "expr": "(\n  sum by (pod) (kube_pod_container_status_waiting{cluster=~\"$cluster\", pod=~\"$pod\"}) == 1\n) * on(pod) group_left(reason) (\n  sum by (pod, reason) (kube_pod_container_status_waiting_reason{cluster=~\"$cluster\", pod=~\"$pod\"}) == 1\n)",
     "legendFormat": "{{cluster}} - {{node}} - {{pod}} - WAITING -> {{reason}}"
    }
   ]
  },
  {
   "title": "Replicas availability",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_statefulset_spec_replicas{cluster=~\"$cluster\", statefulset=\"openvsx-proxy\"}",
     "legendFormat": "{{cluster}} - {{statefulset}} - Desired"
    },
    {
     "expr": "kube_statefulset_status_replicas_available{cluster=~\"$cluster\", statefulset=\"openvsx-proxy\"}",
     "legendFormat": "{{cluster}} - {{statefulset}} - Available replicas"
    },
    {
     "expr": "kube_statefulset_status_replicas_unavailable{cluster=~\"$cluster\", statefulset=\"openvsx-proxy\"}",
     "legendFormat": "{{cluster}} - {{statefulset}} - Unvailable replicas"
    }
   ]
  }
 ]
}