{
 "title": "OpenVSX Mirror",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(http_client_requests_seconds_count, cluster)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(jvm_memory_committed_bytes{cluster=~\"$cluster\", pod=~\"open-vsx.*\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Upstream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_client_requests_seconds_count{cluster=~\"$cluster\", pod=~\"$pod\"}[2m]))",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "total failure ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_client_requests_seconds_count{cluster=~\"$cluster\", pod=~\"$pod\",outcome!~\"SUCCESS|REDIRECTION\"})[2m])/sum(rate(http_client_requests_seconds_count{cluster=~\"$cluster\", pod=~\"$pod\"})[2m])",
     "legendFormat": "total ratio"
    }
   ]
  },
  {
   "title": "failure ratio by status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_client_requests_seconds_count{cluster=~\"$cluster\", pod=~\"$pod\",outcome!~\"SUCCESS|REDIRECTION\"})[2m])/ignoring(status) group_left sum(rate(http_client_requests_seconds_count{cluster=~\"$cluster\", pod=~\"$pod\"})[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "total number of requests",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(http_client_requests_seconds_count{cluster=~\"$cluster\", pod=~\"$pod\"}) by (status,uri) ",
     "legendFormat": "{{uri}} {{outcome}}"
    }
   ]
  },
  { "title": "JVM - Quartz Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "longest in-progress timing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "method_timed_seconds_max{cluster=~\"$cluster\", pod=~\"$pod\"}",
     "legendFormat": "{{class}}"
    }
   ]
  },
  {
   "title": "active in progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "method_timed_seconds_active_count{cluster=~\"$cluster\", pod=~\"$pod\"}",
     "legendFormat": "{{class}}"
    },
    { "legendFormat": "__auto" }
   ]
  },
  { "title": "JVM - Memory/CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{cluster=~\"$cluster\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "used-{{pod}}"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{cluster=~\"$cluster\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "committed-{{pod}}"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{cluster=~\"$cluster\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "max-{{pod}}"
    }
   ]
  },
  {
   "title": "cpu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_usage{cluster=~\"$cluster\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "max memory used",
   "type": "timeseries",
   "description": "used / committed",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max_over_time((jvm_memory_used_bytes{cluster=~\"$cluster\", pod=~\"$pod\", id=\"G1 Old Gen\"}/jvm_memory_committed_bytes{cluster=~\"$cluster\", pod=~\"$pod\", id=\"G1 Old Gen\"})[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "gc overhead",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "jvm_gc_overhead_percent{cluster=~\"$cluster\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JVM - DB connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "idle",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(hikaricp_connections_idle{cluster=~\"$cluster\", pod=~\"$pod\"}) by (pool)",
       "legendFormat": "idle"
      }
     ]
    },
    {
     "title": "active",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(hikaricp_connections_active{cluster=~\"$cluster\", pod=~\"$pod\"}) by (pool)",
       "legendFormat": "idle"
      }
     ]
    },
    {
     "title": "pending",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(hikaricp_connections_pending{cluster=~\"$cluster\", pod=~\"$pod\"}) by (pool)",
       "legendFormat": "pending"
      }
     ]
    },
    {
     "title": "Conn Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "sum(hikaricp_connections_idle{cluster=~\"$cluster\", pod=~\"$pod\"}) by (pool)",
       "legendFormat": "idle"
      },
      {
       "expr": "sum(hikaricp_connections_pending{cluster=~\"$cluster\", pod=~\"$pod\"}) by (pool)",
       "legendFormat": "pending"
      },
      {
       "expr": "sum(hikaricp_connections_active{cluster=~\"$cluster\", pod=~\"$pod\"}) by (pool)",
       "legendFormat": "active"
      }
     ]
    },
    {
     "title": "Timeout Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "expr": "hikaricp_connections_timeout_total{cluster=~\"$cluster\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Connections Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "irate(hikaricp_connections_usage_seconds_sum{cluster=~\"$cluster\", pod=~\"$pod\"}[5m]) / irate(hikaricp_connections_usage_seconds_count{cluster=~\"$cluster\", pod=~\"$pod\"}[5m])",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}