{
 "title": "SSH Gateway Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(gitpod_ws_proxy_ssh_connection_count, cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "All clusters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SSH connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(gitpod_ws_proxy_ssh_connection_count{cluster=~\"(eu|us).*\"})",
     "legendFormat": "All Clusters"
    }
   ]
  },
  {
   "title": "SSH connection rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "rate(sum(gitpod_ws_proxy_ssh_attempt_total{cluster=~\"(eu|us).*\", status=\"success\"}[$__interval]))",
     "legendFormat": "All clusters"
    }
   ]
  },
  {
   "title": "SSH error number (main)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(gitpod_ws_proxy_ssh_attempt_total{cluster=~\"(eu|us).*\", error_type!~\"(OTHERS|WS_NOTFOUND)\", status=\"failed\"}) by (error_type)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "SSH error rate (other)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "rate(sum(gitpod_ws_proxy_ssh_attempt_total{cluster=~\"(eu|us).*\", error_type=~\"(OTHERS|WS_NOTFOUND)\", status=\"failed\"}[$__interval]) by (error_type))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Per clusters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "$cluster: SSH connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "repeat": "cluster",
   "targets": [
    {
     "expr": "sum(gitpod_ws_proxy_ssh_connection_count{cluster=\"$cluster\"})",
     "legendFormat": "All Clusters"
    }
   ]
  },
  {
   "title": "$cluster: SSH connection rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "repeat": "cluster",
   "targets": [
    {
     "expr": "rate(sum(gitpod_ws_proxy_ssh_attempt_total{cluster=\"$cluster\", status=\"success\"}[$__interval]))",
     "legendFormat": "All clusters"
    }
   ]
  },
  {
   "title": "$cluster: SSH error number (main)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "repeat": "cluster",
   "targets": [
    {
     "expr": "sum(gitpod_ws_proxy_ssh_attempt_total{cluster=\"$cluster\", error_type!~\"(OTHERS|WS_NOTFOUND)\", status=\"failed\"}) by (error_type)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "$cluster: SSH error rate (other)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "repeat": "cluster",
   "targets": [
    {
     "expr": "rate(sum(gitpod_ws_proxy_ssh_attempt_total{cluster=\"$cluster\", error_type=~\"(OTHERS|WS_NOTFOUND)\", status=\"failed\"}[$__interval]) by (error_type))",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}