{
 "title": "Supervisor",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Duration Overall Quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(supervisor_client_handling_seconds_bucket{method!=\"InstanceUpdates\"}[1m])) by (le))",
     "legendFormat": "100%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(supervisor_client_handling_seconds_bucket{method!=\"InstanceUpdates\"}[1m])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(supervisor_client_handling_seconds_bucket{method!=\"InstanceUpdates\"}[1m])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.80, sum(rate(supervisor_client_handling_seconds_bucket{method!=\"InstanceUpdates\"}[1m])) by (le))",
     "legendFormat": "80%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(supervisor_client_handling_seconds_bucket{method!=\"InstanceUpdates\"}[1m])) by (le))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "Total Failure Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(supervisor_client_handled_total{err_code!~\"OK|Canceled|PermissionDenied\", job=\"ide-metrics\"}[2m])) by (server) / sum(rate(supervisor_client_handled_total{job=\"ide-metrics\"}[2m])) by (server)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failure Ratio by ErrCode",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (err_code, server) (rate(supervisor_client_handled_total{err_code!~\"OK|Canceled|PermissionDenied\", job=\"ide-metrics\"}[2m]))/ignoring(err_code, server) group_left sum(rate(supervisor_client_handled_total{job=\"ide-metrics\"}[2m]))",
     "legendFormat": "{{err_code}}: {{server}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(supervisor_client_handled_total{}[2m])) by (server)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by Method",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(supervisor_client_handled_total{}[2m])) by (server, method)",
     "legendFormat": "{{method}}: {{server}}"
    }
   ]
  }
 ]
}