// Copyright (c) 2023 Gitpod GmbH. All rights reserved.
// Licensed under the GNU Affero General Public License (AGPL).
// See License.AGPL.txt in the project root for license information.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: gitpod/experimental/v1/idp.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IDPServiceClient is the client API for IDPService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IDPServiceClient interface {
	// GetIDToken produces a new IT token
	GetIDToken(ctx context.Context, in *GetIDTokenRequest, opts ...grpc.CallOption) (*GetIDTokenResponse, error)
}

type iDPServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIDPServiceClient(cc grpc.ClientConnInterface) IDPServiceClient {
	return &iDPServiceClient{cc}
}

func (c *iDPServiceClient) GetIDToken(ctx context.Context, in *GetIDTokenRequest, opts ...grpc.CallOption) (*GetIDTokenResponse, error) {
	out := new(GetIDTokenResponse)
	err := c.cc.Invoke(ctx, "/gitpod.experimental.v1.IDPService/GetIDToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IDPServiceServer is the server API for IDPService service.
// All implementations must embed UnimplementedIDPServiceServer
// for forward compatibility
type IDPServiceServer interface {
	// GetIDToken produces a new IT token
	GetIDToken(context.Context, *GetIDTokenRequest) (*GetIDTokenResponse, error)
	mustEmbedUnimplementedIDPServiceServer()
}

// UnimplementedIDPServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIDPServiceServer struct {
}

func (UnimplementedIDPServiceServer) GetIDToken(context.Context, *GetIDTokenRequest) (*GetIDTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIDToken not implemented")
}
func (UnimplementedIDPServiceServer) mustEmbedUnimplementedIDPServiceServer() {}

// UnsafeIDPServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IDPServiceServer will
// result in compilation errors.
type UnsafeIDPServiceServer interface {
	mustEmbedUnimplementedIDPServiceServer()
}

func RegisterIDPServiceServer(s grpc.ServiceRegistrar, srv IDPServiceServer) {
	s.RegisterService(&IDPService_ServiceDesc, srv)
}

func _IDPService_GetIDToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIDTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IDPServiceServer).GetIDToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gitpod.experimental.v1.IDPService/GetIDToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IDPServiceServer).GetIDToken(ctx, req.(*GetIDTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IDPService_ServiceDesc is the grpc.ServiceDesc for IDPService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IDPService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gitpod.experimental.v1.IDPService",
	HandlerType: (*IDPServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIDToken",
			Handler:    _IDPService_GetIDToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gitpod/experimental/v1/idp.proto",
}
