{
 "title": "ArgoCD",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "interval", "query": "1m,5m,10m,30m,1h,2h,4h,8h" },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(argocd_app_labels, label_environment)"
    }
   },
   {
    "name": "health_status",
    "query": "Healthy,Progressing,Suspended,Missing,Degraded,Unknown"
   },
   { "name": "sync_status", "query": "Synced,OutOfSync,Unknown" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ArgoCD Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{job=\"argocd-server-metrics\"})"
    }
   ]
  },
  {
   "title": "Managed Clusters",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (server) (argocd_cluster_info))"
    }
   ]
  },
  {
   "title": "Managed Applications",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n    argocd_app_info{health_status=~\"$health_status\",sync_status=~\"$sync_status\"} \r\n    * on(name) group_left(label_environment) argocd_app_labels{label_environment=~\"$environment\"}\r\n)"
    }
   ]
  },
  {
   "title": "Repositories Watched",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (repo) (\r\n    argocd_app_info * on(name) group_left argocd_app_labels{label_environment=~\"$environment\"}\r\n))"
    }
   ]
  },
  {
   "title": "Managed Applications",
   "type": "table",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "argocd_app_info{health_status=~\"$health_status\",sync_status=~\"$sync_status\"} \r\n* on(name) group_left(label_environment, label_team) argocd_app_labels{label_environment=~\"$environment\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Application Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Health Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\r\n    argocd_app_info{health_status=~\"$health_status\",sync_status=~\"$sync_status\",health_status!=\"\"} \r\n    * on(name) group_left argocd_app_labels{label_environment=~\"$environment\"}\r\n) by (health_status)",
     "legendFormat": "{{health_status}}"
    }
   ]
  },
  {
   "title": "Sync Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\r\n    argocd_app_info{health_status=~\"$health_status\",sync_status=~\"$sync_status\",health_status!=\"\"}\r\n    * on(name) group_left argocd_app_labels{label_environment=~\"$environment\"}\r\n) by (sync_status)",
     "legendFormat": "{{sync_status}}"
    }
   ]
  },
  {
   "title": "Sync Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Sync Activity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\r\n    round(\r\n        increase(\r\n            argocd_app_sync_total[$interval]\r\n            * on(name) group_left argocd_app_labels{label_environment=~\"$environment\"}\r\n        )\r\n    )\r\n) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sync Failures",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(\r\n    round(\r\n        increase(\r\n            argocd_app_sync_total{phase=~\"Error|Failed\"}[$interval]\r\n            * on(name) group_left argocd_app_labels{label_environment=~\"$environment\"}\r\n        )\r\n    )\r\n) by (name, phase)",
     "legendFormat": "{{phase}}: {{name}}"
    }
   ]
  },
  {
   "title": "Controller Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Reconciliation Activity (not filtered by environment or team)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(\r\n    increase(\r\n        argocd_app_reconcile_count[$interval]\r\n    )\r\n) ",
       "legendFormat": "Reconciliation rate"
      }
     ]
    },
    {
     "title": "Reconciliation Performance (not filtered by environment or team)",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "sum(\r\n    increase(\r\n        argocd_app_reconcile_bucket[$interval]\r\n    )\r\n) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "K8s API Activity",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(argocd_app_k8s_request_total[$interval])) by (verb, resource_kind)",
       "legendFormat": "{{verb}} {{resource_kind}}"
      }
     ]
    },
    {
     "title": "Workqueue Depth",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(workqueue_depth{name=~\"app_.*\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Pending kubectl run",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(argocd_kubectl_exec_pending) by (command)",
       "legendFormat": "{{command}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Controller Telemetry",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{job=\"argocd-metrics\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(process_cpu_seconds_total{job=\"argocd-metrics\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_goroutines{job=\"argocd-metrics\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Resource Objects Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(argocd_cluster_api_resource_objects) by (server)",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "API Resources Count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(argocd_cluster_api_resources) by (server)",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Cluster Events Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(argocd_cluster_events_total[$interval])) by (server)",
       "legendFormat": "{{server}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Repo Server Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Git Requets (ls-remote)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(argocd_git_request_total{request_type=\"ls-remote\"}[10m])) by (repo)",
       "legendFormat": "{{repo}}"
      }
     ]
    },
    {
     "title": "Git Requests (checkout)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(argocd_git_request_total{request_type=\"fetch\"}[10m])) by (repo)",
       "legendFormat": "{{repo}}"
      }
     ]
    },
    {
     "title": "Git Ls-Remote Performance",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "sum(increase(argocd_git_request_duration_seconds_bucket{request_type=\"ls-remote\"}[$interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Git Fetch Performance",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "targets": [
      {
       "expr": "sum(increase(argocd_git_request_duration_seconds_bucket{request_type=\"fetch\"}[$interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Memory Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{job=\"argocd-repo-server\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_goroutines{job=\"argocd-repo-server\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Server Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{job=\"argocd-server-metrics\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_goroutines{job=\"argocd-server-metrics\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "GC Time Quantiles",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_gc_duration_seconds{job=\"argocd-server-metrics\", quantile=\"1\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 55 }, "options": { "content": "#### gRPC Services:" } },
    {
     "title": "ApplicationService Requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handled_total{job=\"argocd-server-metrics\",grpc_service=\"application.ApplicationService\"}[$interval])) by (grpc_code, grpc_method)",
       "legendFormat": "{{grpc_code}},{{grpc_method}}"
      }
     ]
    },
    {
     "title": "ClusterService Requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handled_total{job=\"argocd-server-metrics\",grpc_service=\"cluster.ClusterService\"}[$interval])) by (grpc_code, grpc_method)",
       "legendFormat": "{{grpc_code}},{{grpc_method}}"
      }
     ]
    },
    {
     "title": "ProjectService Requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handled_total{job=\"argocd-server-metrics\",grpc_service=\"project.ProjectService\"}[$interval])) by (grpc_code, grpc_method)",
       "legendFormat": "{{grpc_code}},{{grpc_method}}"
      }
     ]
    },
    {
     "title": "RepositoryService Requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handled_total{job=\"argocd-server-metrics\",grpc_service=\"repository.RepositoryService\"}[$interval])) by (grpc_code, grpc_method)",
       "legendFormat": "{{grpc_code}},{{grpc_method}}"
      }
     ]
    },
    {
     "title": "SessionService Requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handled_total{job=\"argocd-server-metrics\",grpc_service=\"session.SessionService\"}[$interval])) by (grpc_code, grpc_method)",
       "legendFormat": "{{grpc_code}},{{grpc_method}}"
      }
     ]
    },
    {
     "title": "VersionService Requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handled_total{job=\"argocd-server-metrics\",grpc_service=\"version.VersionService\"}[$interval])) by (grpc_code, grpc_method)",
       "legendFormat": "{{grpc_code}},{{grpc_method}}"
      }
     ]
    },
    {
     "title": "AccountService Requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handled_total{job=\"argocd-server-metrics\",grpc_service=\"account.AccountService\"}[$interval])) by (grpc_code, grpc_method)",
       "legendFormat": "{{grpc_code}},{{grpc_method}}"
      }
     ]
    },
    {
     "title": "SettingsService Requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handled_total{job=\"argocd-server-metrics\",grpc_service=\"settings.SettingsService\"}[$interval])) by (grpc_code, grpc_method)",
       "legendFormat": "{{grpc_code}},{{grpc_method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Redis Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Requests by result",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(argocd_redis_request_total[$interval])) by (failed)"
      }
     ]
    }
   ]
  }
 ]
}