{
 "title": "Gitpod / Component / ws-manager-mk2",
 "tags": [ "gitpod-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"ws-manager-mk2\"}, cluster)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{cluster=~\"$cluster\", pod=~\"ws-manager-mk2-.*\"}, node)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{cluster=~\"$cluster\", node=~\"$node\", pod=~\"ws-manager-mk2-.*\"}, pod)"
    }
   },
   {
    "name": "grpc_method",
    "label": "gRPC Method",
    "query": {
     "query": "label_values(grpc_server_handled_total{grpc_service=\"wsman.WorkspaceManager\", cluster=~\"$cluster\"}, grpc_method)"
    }
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "controller",
    "label": "Controller",
    "query": {
     "query": "label_values(workqueue_depth{pod=~\"$pod\"}, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "ws-manager-mk2 Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Workspace count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(gitpod_ws_manager_mk2_workspace_phase_total{cluster=~\"$cluster\"}) by (type, cluster, phase)",
     "legendFormat": "{{cluster}} - {{ type }} - {{phase}}"
    }
   ]
  },
  {
   "title": "Workspace Starts",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(\n  rate(gitpod_ws_manager_mk2_workspace_startup_seconds_count{cluster=~\"$cluster\"}[1m])\n) by (cluster, type)",
     "legendFormat": "{{cluster}} - {{type}}"
    },
    {
     "expr": "sum(rate(gitpod_ws_manager_mk2_workspace_starts_failure_total{cluster=~\"$cluster\"}[1m])) by (cluster, type)",
     "legendFormat": "Failures: {{cluster}} - {{type}}"
    }
   ]
  },
  {
   "title": "Workspace Stops",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(\n  rate(gitpod_ws_manager_mk2_workspace_stops_total{cluster=~\"$cluster\"}[$__rate_interval])\n) by (cluster, reason)",
     "legendFormat": "{{cluster}} - {{reason}}"
    }
   ]
  },
  {
   "title": "Regular workspace startup time",
   "type": "heatmap",
   "description": "Avg is shown here, just so we know that we are configuring our buckets right.\n\nMore info about how avg can help us with bucket configuration can be seen at Tom Wilkie's RED Method talk.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(\n    rate(gitpod_ws_manager_mk2_workspace_startup_seconds_bucket{cluster=~\"$cluster\", type=\"Regular\"}[5m])\n  ) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "ImageBuild startup time",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 12 },
   "targets": [
    {
     "expr": "sum(\n    rate(gitpod_ws_manager_mk2_workspace_startup_seconds_bucket{cluster=~\"$cluster\", type=\"ImageBuild\"}[5m])\n  ) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Prebuild startup time",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum(\n    rate(gitpod_ws_manager_mk2_workspace_startup_seconds_bucket{cluster=~\"$cluster\", type=\"Prebuild\"}[5m])\n  ) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Workspace Failures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(\n  rate(gitpod_ws_manager_mk2_workspace_failure_total{cluster=~\"$cluster\"}[$__rate_interval])\n) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  { "title": "Controller Manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Work Queue Add Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{job=\"ws-manager-mk2\", pod=~\"$pod\", name=~\"$controller\"}[5m])) by (pod, name)",
     "legendFormat": "{{pod}} {{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Depth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(workqueue_depth{job=\"ws-manager-mk2\", pod=~\"$pod\", name=~\"$controller\"}) by (pod, name)",
     "legendFormat": "{{pod}} {{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 22 },
   "targets": [
    {
     "expr": "sum(rate(workqueue_queue_duration_seconds_bucket{job=\"ws-manager-mk2\", pod=~\"$pod\", name=~\"$controller\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kube API Request Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"ws-manager-mk2\", pod=~\"$pod\",code=~\"2..\"}[5m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"ws-manager-mk2\", pod=~\"$pod\",code=~\"3..\"}[5m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"ws-manager-mk2\", pod=~\"$pod\",code=~\"4..\"}[5m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"ws-manager-mk2\", pod=~\"$pod\",code=~\"5..\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Reconciliations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{job=\"ws-manager-mk2\", pod=~\"$pod\", controller=~\"$controller\"}[5m])) by (pod, controller, result)",
     "legendFormat": "{{pod}} {{controller}} {{result}}"
    }
   ]
  },
  {
   "title": "Reconcile Work Duration",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 31 },
   "targets": [
    {
     "expr": "sum(rate(workqueue_work_duration_seconds_bucket{job=\"ws-manager-mk2\", pod=~\"$pod\", name=~\"$controller\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gRPC Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "gRPC calls handled (Server-side)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{job=\"ws-manager-mk2\", cluster=~\"$cluster\", grpc_method=~\"$grpc_method\"}[1m])) by (grpc_code, grpc_method, cluster)",
     "legendFormat": "{{cluster}} - {{grpc_method}} - {{grpc_code}}"
    }
   ]
  },
  {
   "title": "gRPC start and finish rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{job=\"ws-manager-mk2\", cluster=~\"$cluster\", grpc_method=~\"$grpc_method\"}[1m])) by (grpc_code, grpc_method, cluster)",
     "legendFormat": "{{cluster}} - {{grpc_method}} - Started"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{job=\"ws-manager-mk2\", cluster=~\"$cluster\", grpc_method=~\"$grpc_method\"}[1m])) by (grpc_method, cluster)",
     "legendFormat": "{{cluster}} - {{grpc_method}} - Finished"
    }
   ]
  },
  {
   "title": "$grpc_method: Time handling gRPC calls",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "repeat": "grpc_method",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum(\n    rate(grpc_server_handling_seconds_bucket{job=\"ws-manager-mk2\", cluster=~\"$cluster\", grpc_method=~\"$grpc_method\"}[5m])\n  ) by (cluster, grpc_method, le)\n)",
     "legendFormat": "{{cluster}} - {{grpc_method}} - 99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, \n  sum(\n    rate(grpc_server_handling_seconds_bucket{job=\"ws-manager-mk2\", cluster=~\"$cluster\", grpc_method=~\"$grpc_method\"}[5m])\n  ) by (cluster, grpc_method, le)\n)",
     "legendFormat": "{{cluster}} - {{grpc_method}} - 95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, \n  sum(\n    rate(grpc_server_handling_seconds_bucket{job=\"ws-manager-mk2\", cluster=~\"$cluster\", grpc_method=~\"$grpc_method\"}[5m])\n  ) by (cluster, grpc_method, le)\n)",
     "legendFormat": "{{cluster}} - {{grpc_method}} - 50th Percentile"
    },
    {
     "expr": "  sum(\n    rate(grpc_server_handling_seconds_sum{job=\"ws-manager-mk2\", cluster=~\"$cluster\", grpc_method=\"$grpc_method\"}[5m])\n  ) by (cluster, grpc_method)\n  /\n  sum(\n    rate(grpc_server_handling_seconds_count{job=\"ws-manager-mk2\", cluster=~\"$cluster\", grpc_method=\"$grpc_method\"}[5m])\n  ) by (cluster, grpc_method)",
     "legendFormat": "{{cluster}} - {{grpc_method}} - avg"
    }
   ]
  },
  {
   "title": "Pod Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Container image version",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "kube_pod_container_info{cluster=~\"$cluster\", pod=~\"$pod\", image=~\".+\", container=\"ws-manager-mk2\"}",
     "legendFormat": "{{cluster}} - {{image}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(container_cpu_usage_seconds_total{container!=\"POD\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)",
     "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Cores being used"
    }
   ]
  },
  {
   "title": "CPU Saturation",
   "type": "graph",
   "description": "Saturation > 100% means that the container is requesting more than its limits.\n\nKubernetes will start to throttle CPU when that happens. That's a sign of degraded performance.\n\n'No Data' indicates that the pod has no CPU limits.",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 69 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(container_cpu_usage_seconds_total{container!=\"POD\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)\n/\nsum(\n  kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", cluster=\"$cluster\", pod=~\"$pod\"}\n) by (pod, cluster, node)\n",
     "legendFormat": "{{cluster}} - {{node} - {{pod}} - CPU Saturation"
    },
    {
     "expr": "sum(\nrate(container_cpu_cfs_throttled_seconds_total{container!=\"POD\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod)",
     "legendFormat": "{{pod}} - CPU Throttles"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"POD\", container!=\"\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}) by (pod, cluster, node)",
     "legendFormat": "{{cluster}} - {{node}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Saturation",
   "type": "graph",
   "description": "Memory can't be throttled. When a container reaches 100% of its memory limits,  Kubernetes will kill the container and restart it.\n\n'No Data' indicates that the pod doesn't have Memory limits.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\nrate(container_memory_working_set_bytes{container!=\"POD\", container!=\"\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)\n/\nsum(\n  kube_pod_container_resource_limits{container!=\"POD\", cluster=\"$cluster\", pod=~\"$pod\", resource=\"memory\"}\n) by (pod, cluster, node)\n",
     "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Memory Saturation"
    }
   ]
  },
  {
   "title": "Network Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum (\n  rate(container_network_receive_bytes_total{container!=\"POD\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)",
     "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Received"
    },
    {
     "expr": "sum (\n  rate(container_network_transmit_bytes_total{container!=\"POD\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)",
     "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Transmitted"
    }
   ]
  },
  {
   "title": "Network Saturation (Packets Dropped)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 83 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum (\n  rate(container_network_receive_packets_dropped_total{container!=\"POD\", pod!=\"\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)",
     "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Receive"
    },
    {
     "expr": "sum (\n  rate(container_network_transmit_packets_dropped_total{container!=\"POD\", pod!=\"\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)",
     "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Transmit"
    }
   ]
  },
  {
   "title": "Network Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 83 },
   "yaxes": [
    { "format": "Errors/s" }
   ],
   "targets": [
    {
     "expr": "sum (\n  rate(container_network_receive_errors_total{container!=\"POD\", pod!=\"\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)",
     "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Received"
    },
    {
     "expr": "sum (\n  rate(container_network_transmit_errors_total{container!=\"POD\", pod!=\"\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)",
     "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Transmitted"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kube_pod_container_status_restarts_total{cluster=~\"$cluster\", pod=~\"$pod\"}[1m])",
     "legendFormat": "{{cluster}} - {{kubernetes_pod_node_name}} - {{pod}} "
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_running{cluster=~\"$cluster\", pod=~\"$pod\"} == 1 ",
     "legendFormat": "{{pod}}  - RUNNING"
    },
    {
     "expr": "(\n  sum by (pod) (kube_pod_container_status_terminated{cluster=~\"$cluster\", pod=~\"$pod\"}) == 1\n) * on(pod) group_left(reason) (\n  sum by (pod, reason) (kube_pod_container_status_terminated_reason{cluster=~\"$cluster\", pod=~\"$pod\"}) == 1\n)",
     "legendFormat": "{{pod}}  - TERMINATED -> {{reason}}"
    },
    {
     "expr": "(\n  sum by (pod) (kube_pod_container_status_waiting{cluster=~\"$cluster\", pod=~\"$pod\"}) == 1\n) * on(pod) group_left(reason) (\n  sum by (pod, reason) (kube_pod_container_status_waiting_reason{cluster=~\"$cluster\", pod=~\"$pod\"}) == 1\n)",
     "legendFormat": "{{pod}}  - WAITING -> {{reason}}"
    }
   ]
  },
  {
   "title": "Replicas availability",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{cluster=~\"$cluster\", deployment=\"ws-manager-mk2\"}",
     "legendFormat": "{{cluster}} - {{deployment}} - Desired"
    },
    {
     "expr": "kube_deployment_status_replicas_available{cluster=~\"$cluster\", deployment=\"ws-manager-mk2\"}",
     "legendFormat": "{{cluster}} - {{deployment}} - Available replicas"
    },
    {
     "expr": "kube_deployment_status_replicas_unavailable{cluster=~\"$cluster\", deployment=\"ws-manager-mk2\"}",
     "legendFormat": "{{cluster}} - {{deployment}} - Unvailable replicas"
    }
   ]
  },
  {
   "title": "Go Runtime Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Usage (as seen by the runtime process)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{cluster=~\"$cluster\", job=\"ws-manager-mk2\", pod=~\"$pod\"}",
     "legendFormat": "{{cluster}} - {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage (as seen by the runtime process)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 100 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{cluster=~\"$cluster\", job=\"ws-manager-mk2\", pod=~\"$pod\"}[5m])",
     "legendFormat": "{{cluster}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_sys_bytes{cluster=~\"$cluster\", job=\"ws-manager-mk2\", pod=~\"$pod\"}",
     "legendFormat": "{{cluster}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Allocation rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 109 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{cluster=~\"$cluster\", job=\"ws-manager-mk2\", pod=~\"$pod\"}[5m])",
     "legendFormat": "{{cluster}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{cluster=~\"$cluster\", job=\"ws-manager-mk2\", pod=~\"$pod\"}",
     "legendFormat": "{{cluster}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Garbage collection time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 118 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{cluster=~\"$cluster\", job=\"ws-manager-mk2\", pod=~\"$pod\", quantile=\"0.5\"}",
     "legendFormat": "{{cluster}} - {{pod}} - GC Duration - 50th percentile"
    },
    {
     "expr": "go_gc_duration_seconds{cluster=~\"$cluster\", job=\"ws-manager-mk2\", pod=~\"$pod\", quantile=\"0.75\"}",
     "legendFormat": "{{cluster}} - {{pod}} - GC Duration - 75th percentile"
    },
    {
     "expr": "go_gc_duration_seconds{cluster=~\"$cluster\", job=\"ws-manager-mk2\", pod=~\"$pod\", quantile=\"1\"}",
     "legendFormat": "{{cluster}} - {{pod}} - GC Duration - 100th percentile"
    }
   ]
  }
 ]
}