// Copyright (c) 2022 Gitpod GmbH. All rights reserved.
// Licensed under the GNU Affero General Public License (AGPL).
// See License-AGPL.txt in the project root for license information.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: gitpod/stable/v1/yolo.proto

package v1connect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	v1 "github.com/gitpod-io/gitpod/public-api/stable/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// YoloServiceName is the fully-qualified name of the YoloService service.
	YoloServiceName = "gitpod.stable.v1.YoloService"
)

// YoloServiceClient is a client for the gitpod.stable.v1.YoloService service.
type YoloServiceClient interface {
	DoSomething(context.Context, *connect_go.Request[v1.DoSomethingRequest]) (*connect_go.Response[v1.DoSomethingResponse], error)
}

// NewYoloServiceClient constructs a client for the gitpod.stable.v1.YoloService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewYoloServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) YoloServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &yoloServiceClient{
		doSomething: connect_go.NewClient[v1.DoSomethingRequest, v1.DoSomethingResponse](
			httpClient,
			baseURL+"/gitpod.stable.v1.YoloService/DoSomething",
			opts...,
		),
	}
}

// yoloServiceClient implements YoloServiceClient.
type yoloServiceClient struct {
	doSomething *connect_go.Client[v1.DoSomethingRequest, v1.DoSomethingResponse]
}

// DoSomething calls gitpod.stable.v1.YoloService.DoSomething.
func (c *yoloServiceClient) DoSomething(ctx context.Context, req *connect_go.Request[v1.DoSomethingRequest]) (*connect_go.Response[v1.DoSomethingResponse], error) {
	return c.doSomething.CallUnary(ctx, req)
}

// YoloServiceHandler is an implementation of the gitpod.stable.v1.YoloService service.
type YoloServiceHandler interface {
	DoSomething(context.Context, *connect_go.Request[v1.DoSomethingRequest]) (*connect_go.Response[v1.DoSomethingResponse], error)
}

// NewYoloServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewYoloServiceHandler(svc YoloServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	mux := http.NewServeMux()
	mux.Handle("/gitpod.stable.v1.YoloService/DoSomething", connect_go.NewUnaryHandler(
		"/gitpod.stable.v1.YoloService/DoSomething",
		svc.DoSomething,
		opts...,
	))
	return "/gitpod.stable.v1.YoloService/", mux
}

// UnimplementedYoloServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedYoloServiceHandler struct{}

func (UnimplementedYoloServiceHandler) DoSomething(context.Context, *connect_go.Request[v1.DoSomethingRequest]) (*connect_go.Response[v1.DoSomethingResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("gitpod.stable.v1.YoloService.DoSomething is not implemented"))
}
