{
 "title": "Cardinality Management - Overview",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(metrics_total, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "💡Tips for metrics",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "## Individual metrics with a high number of series associated with them:\n\n* Could you drop some labels on that metric to reduce its cardinality?\n\n* Could you drop the entire metric?\n\n* Could you replace the large number of unique label/label value pairs?"
   }
  },
  {
   "title": "Total Metrics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_total{cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 15 - High cardinality metrics",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sort_desc(\r\n    topk(15, \r\n      sum(metric:timeseries_total{cluster=~\"$cluster\"}) by (metric)\r\n    )\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sort_desc(\r\n    topk(15, \r\n        sum(metric:timeseries_total{cluster=~\"$cluster\"}) by (metric) / sum(metric:timeseries_total{cluster=~\"$cluster\"})\r\n    )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total timeseries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metric:timeseries_total{cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}