{
 "title": "Preview Environments",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kubevirt_info, cluster)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(kubevirt_vmi_memory_used_total_bytes{cluster=~\"$cluster\"},  kubernetes_vmi_label_kubevirt_io_nodeName)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Running Previews",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kubevirt_vmi_memory_used_total_bytes{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Preview Start SLO",
   "type": "text",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 8 },
   "options": {
    "content": "We have an SLO for preview starts in Honeycomb. You can see the SLO [here](https://ui.honeycomb.io/gitpod/datasets/werft/slo/zRm48xoKMXf/Preview-Start). Alternatively you can use [this query](https://ui.honeycomb.io/gitpod/datasets/werft/result/a64cNk4sArf) to dig into succesful and failed SLI events. The definition of the SLO can be found [here](https://www.notion.so/gitpod/Preview-Environment-Service-Level-Indicators-SLIs-55b649ad17774f279c142af55ad2fec7#f483f73aa4974ad3b8b6825fa2f251fa)."
   }
  },
  { "title": "Previews per node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "$node: Running Previews",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "repeat": "node",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kubevirt_vmi_memory_used_total_bytes{cluster=~\"$cluster\", kubernetes_vmi_label_kubevirt_io_nodeName=\"$node\"})"
    }
   ]
  },
  {
   "title": "Virtual Machines Starts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "VMI Start Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kubevirt_vmi_phase_transition_time_from_creation_seconds_count{phase=\"Running\", cluster=~\"$cluster\"}[5m]))",
       "legendFormat": " Starts per second"
      }
     ]
    }
   ]
  },
  {
   "title": "KubeVirt API Access",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Server - Read Requests Rate",
     "type": "graph",
     "description": "How many read requests (LIST,GET,WATCH) per second do the apiservers get by code?",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(apiserver_request_total{group=~\".*kubevirt.*\", verb=~\"LIST|GET\"}[5m])) by (code, group)",
       "legendFormat": "{{ code }}  {{group}} "
      }
     ]
    },
    {
     "title": "API Server - Read Requests Duration",
     "type": "graph",
     "description": "How many seconds is the 99th percentile for reading (LIST|WATCH|GET) a given resource?",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(apiserver_request_duration_seconds_bucket{group=\"kubevirt.io\", verb=~\"LIST|GET\", scope=\"cluster\"}[5m])) by (le, resource, verb))",
       "legendFormat": "{{verb}} {{ resource }}"
      }
     ]
    },
    {
     "title": "API Server - Write Requests Rate",
     "type": "graph",
     "description": "How many write requests (POST|PUT|PATCH|DELETE) per second do the apiservers get by code?",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(rest_client_requests_total{pod=~\"virt-controller.*|virt-handler.*|virt-operator.*|virt-api.*|vm.*|hco.*|kubevirt.*\", container!=\"\", method=~\"POST|PUT|PATCH|DELETE\"}[2m])) by (code, group, container, job, verb, method) > 0",
       "legendFormat": "{{container}} - {{method}} - {{code}}"
      }
     ]
    },
    {
     "title": "API Server - Write Requests Duration",
     "type": "graph",
     "description": "How many seconds is the 99th percentile for writing (POST|PUT|PATCH|DELETE) a given resource?",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(apiserver_request_duration_seconds_bucket{group=\"kubevirt.io\", verb=~\"POST|PUT|PATCH|DELETE\"}[5m])) by (le, verb, resource)) > 0",
       "legendFormat": "{{ resource }} - {{verb}}"
      }
     ]
    },
    {
     "title": "API Client - Read Requests Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(rest_client_requests_total{ pod=~\"virt-controller.*|virt-handler.*|virt-operator.*|virt-api.*|vm.*|hco.*|kubevirt.*\", container!=\"\", method=~\"GET|LIST\"}[2m])) by (code, container, job, verb, method) > 0",
       "legendFormat": "{{container}} - {{method}} - {{code}}"
      }
     ]
    },
    {
     "title": "API Client - Read Requests Duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(rest_client_request_latency_seconds_bucket{verb=~\"GET|LIST\", container!=\"\"}[2m])) by (le, verb, container)) > 0",
       "legendFormat": "{{container}} - {{verb}}"
      }
     ]
    },
    {
     "title": "API Client - Write Requests Rate",
     "type": "graph",
     "description": "How many write requests (POST|PUT|PATCH|DELETE) per second do the apiservers get by code?",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(rest_client_requests_total{pod=~\"virt-controller.*|virt-handler.*|virt-operator.*|virt-api.*|vm.*|hco.*|kubevirt.*\", container!=\"\", method=~\"POST|PUT|PATCH|DELETE\"}[2m])) by (code, container, job, verb, method) > 0",
       "legendFormat": "{{container}} - {{method}} - {{code}}"
      }
     ]
    },
    {
     "title": "API Client - Write Requests Duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(rest_client_request_latency_seconds_bucket{verb=~\"POST|PUT|PATCH|DELETE\", container!=\"\"}[2m])) by (le, verb, container)) > 0",
       "legendFormat": "{{container}} - {{verb}}"
      }
     ]
    }
   ]
  }
 ]
}